stages:
  create_dataset:
    cmd: python src/create_dataset.py
    deps:
    - src/create_dataset.py
    outs:
    - data/breast_cancer.csv
  train_model:
    cmd: python src/train.py
    deps:
    - data/breast_cancer.csv
    - src/train.py
    outs:
    - models/model.pkl
